In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('homeprices_mv.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

Clear Data

In [5]:
import math
df.bedrooms.fillna(math.floor(df.bedrooms.median()),inplace=True)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [7]:
reg.predict([[3000,3,40]])

c:\Users\sr sawant\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

# Export Model

In [8]:
import pickle

In [9]:
with open('price_model','wb') as f:
    pickle.dump(reg,f)

In [10]:
with open('price_model','rb') as f:
    mb = pickle.load(f)

In [12]:
mb.predict([[3000,3,40]])

c:\Users\sr sawant\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

people say that joblib is used essentially when there are large numpy arrays

In [15]:
import joblib

joblib.dump(reg,"price_pred")
mj = joblib.load("price_pred")

In [16]:
mb.predict([[3000,3,40]])

c:\Users\sr sawant\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

# Excercise

In [2]:
edf = pd.read_csv('hiring.csv',names=["experience","test_score","interview_score","salary"],skiprows=[0])
edf

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [3]:
from word2number.w2n import word_to_num
import math
edf.experience.fillna("zero",inplace=True)
edf.test_score.fillna(math.floor(edf.test_score.median()),inplace=True)
edf

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [4]:
edf['experience'] = edf.experience.map(lambda x : word_to_num(x))

In [5]:
edf

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [6]:
ereg = linear_model.LinearRegression()
ereg.fit(edf[['experience','test_score','interview_score']],edf.salary)

LinearRegression()

In [7]:
ereg.predict([[2,9,6]])

c:\Users\sr sawant\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [8]:
ereg.predict([[12,10,10]])

c:\Users\sr sawant\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])